Assuming unrestricted shared filesystem usage.
None
host: JingfengdeMacBook-Pro.local
Building DAG of jobs...
Using shell: /opt/homebrew/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job                count
---------------  -------
all                    1
pope_evaluation        3
total                  4

Select jobs to execute...
Execute 3 jobs...
[Tue Apr  8 18:39:24 2025]
localrule pope_evaluation:
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-random/pope_goldens.pkl, results/qwen2/pope/results/pope-random/pope.done
    jobid: 1
    reason: Missing output files: results/qwen2/pope/golden/pope-random/pope_goldens.pkl
    wildcards: pope_type=random
    resources: tmpdir=/var/folders/4t/h09q0hsd41541c_5xt80467c0000gn/T

[Tue Apr  8 18:39:24 2025]
localrule pope_evaluation:
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-popular/pope_goldens.pkl, results/qwen2/pope/results/pope-popular/pope.done
    jobid: 3
    reason: Missing output files: results/qwen2/pope/golden/pope-popular/pope_goldens.pkl
    wildcards: pope_type=popular
    resources: tmpdir=/var/folders/4t/h09q0hsd41541c_5xt80467c0000gn/T

[Tue Apr  8 18:39:24 2025]
localrule pope_evaluation:
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-adversarial/pope_goldens.pkl, results/qwen2/pope/results/pope-adversarial/pope.done
    jobid: 4
    reason: Missing output files: results/qwen2/pope/golden/pope-adversarial/pope_goldens.pkl
    wildcards: pope_type=adversarial
    resources: tmpdir=/var/folders/4t/h09q0hsd41541c_5xt80467c0000gn/T

Waiting for more resources.
RuleException:
CalledProcessError in file "/Users/jingfengsun/Documents/model/models/src/Snakefile", line 89:
Command 'set -euo pipefail;  
        python scripts/evaluate_pope.py --model_name qwen2         --local_pope_path data/pope-coco         --remote_coco_path /home/qwen2-vl-72b-instruct/POPE-main/data/coco         --pope_type adversarial         --golden_save_path /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/golden/pope-adversarial         --results_folder /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-adversarial         --api_base http://localhost:2000/v1/
        touch /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-adversarial/pope.done' returned non-zero exit status 1.
[Tue Apr  8 18:39:36 2025]
Error in rule pope_evaluation:
    message: None
    jobid: 4
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-adversarial/pope_goldens.pkl, results/qwen2/pope/results/pope-adversarial/pope.done
    shell:
        
        python scripts/evaluate_pope.py --model_name qwen2         --local_pope_path data/pope-coco         --remote_coco_path /home/qwen2-vl-72b-instruct/POPE-main/data/coco         --pope_type adversarial         --golden_save_path /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/golden/pope-adversarial         --results_folder /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-adversarial         --api_base http://localhost:2000/v1/
        touch /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-adversarial/pope.done
        
        (command exited with non-zero exit code)
Removing output files of failed job pope_evaluation since they might be corrupted:
results/qwen2/pope/golden/pope-adversarial/pope_goldens.pkl
RuleException:
CalledProcessError in file "/Users/jingfengsun/Documents/model/models/src/Snakefile", line 89:
Command 'set -euo pipefail;  
        python scripts/evaluate_pope.py --model_name qwen2         --local_pope_path data/pope-coco         --remote_coco_path /home/qwen2-vl-72b-instruct/POPE-main/data/coco         --pope_type popular         --golden_save_path /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/golden/pope-popular         --results_folder /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-popular         --api_base http://localhost:2000/v1/
        touch /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-popular/pope.done' returned non-zero exit status 1.
[Tue Apr  8 18:39:37 2025]
Error in rule pope_evaluation:
    message: None
    jobid: 3
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-popular/pope_goldens.pkl, results/qwen2/pope/results/pope-popular/pope.done
    shell:
        
        python scripts/evaluate_pope.py --model_name qwen2         --local_pope_path data/pope-coco         --remote_coco_path /home/qwen2-vl-72b-instruct/POPE-main/data/coco         --pope_type popular         --golden_save_path /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/golden/pope-popular         --results_folder /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-popular         --api_base http://localhost:2000/v1/
        touch /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-popular/pope.done
        
        (command exited with non-zero exit code)
Removing output files of failed job pope_evaluation since they might be corrupted:
results/qwen2/pope/golden/pope-popular/pope_goldens.pkl
[Tue Apr  8 18:39:37 2025]
Finished jobid: 1 (Rule: pope_evaluation)
1 of 4 steps (25%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Tue Apr  8 18:39:37 2025]
Error in rule pope_evaluation:
    message: None
    jobid: 3
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-popular/pope_goldens.pkl, results/qwen2/pope/results/pope-popular/pope.done
    shell:
        
        python scripts/evaluate_pope.py --model_name qwen2         --local_pope_path data/pope-coco         --remote_coco_path /home/qwen2-vl-72b-instruct/POPE-main/data/coco         --pope_type popular         --golden_save_path /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/golden/pope-popular         --results_folder /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-popular         --api_base http://localhost:2000/v1/
        touch /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-popular/pope.done
        
        (command exited with non-zero exit code)
[Tue Apr  8 18:39:37 2025]
Error in rule pope_evaluation:
    message: None
    jobid: 4
    input: .deepeval, data/pope-coco, scripts/evaluate_pope.py
    output: results/qwen2/pope/golden/pope-adversarial/pope_goldens.pkl, results/qwen2/pope/results/pope-adversarial/pope.done
    shell:
        
        python scripts/evaluate_pope.py --model_name qwen2         --local_pope_path data/pope-coco         --remote_coco_path /home/qwen2-vl-72b-instruct/POPE-main/data/coco         --pope_type adversarial         --golden_save_path /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/golden/pope-adversarial         --results_folder /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-adversarial         --api_base http://localhost:2000/v1/
        touch /Users/jingfengsun/Documents/model/models/src/results/qwen2/pope/results/pope-adversarial/pope.done
        
        (command exited with non-zero exit code)
Complete log(s): /Users/jingfengsun/Documents/model/models/src/.snakemake/log/2025-04-08T183924.265181.snakemake.log
WorkflowError:
At least one job did not complete successfully.
